name: Release

run-name: Patch QQ

# 控制工作流何时运行
on:
  schedule:
  - cron: '30 1 * * 4'
  # Runs at 01:30, only on Thursday.
  # Actions schedules run at most every 5 minutes using UTC time.
  # “肯德基疯狂星期四”仅限9:30-23:00供应
  # 上海市、广东省、福建省、海南省、广西壮族自治区等部分地区仅限10:30-23:00供应，具体以餐厅实际营业时间为准。

  # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [release]

  # 仅供测试：每次提交时运行工作流
  push:
    branches: [ "main" ]

  # 允许手动运行工作流
  workflow_dispatch:

  # 新增Star时立即运行
  # 注意：此项不应长期保持开启！
  # watch:
  #   types: [started]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Download Custom QQ 下载自定义版本QQ
      # 官方直链：https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_9.1.10_64.apk
        run: wget -O QQ-9.1.10.apk https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_9.1.10_64.apk

      - name: Download Latest QQ 下载最新版QQ
        run: |
          response=$(curl -s -X POST -H "Content-Type: application/json" -d '{"packagename":"com.tencent.mobileqq"}' https://upage.html5.qq.com/wechat-apkinfo)
          response=$(echo "$response" | tr -cd '[:print:]')
          version_name=$(echo "$response" | jq -r '.app_detail_records."com.tencent.mobileqq".apk_all_data.version_name')
          download_url=$(echo "$response" | jq -r '.app_detail_records."com.tencent.mobileqq".apk_all_data.url')
          echo "获取到最新版本号: $version_name"
          echo "直链下载地址: $download_url"
          wget -nv -U "Mozilla/5.0" -O "QQ-$version_name-latest.apk" $download_url

      # 下载LSPatch
      - name: Download LSPatch 下载LSPatch
        # run: gh release download -O LSPatch.jar --repo LSPosed/LSPatch --pattern '*.
        # JingMatrix 维护的 LSPatch 分支已适配 Android 15，若在高版本遇到兼容性问题可考虑使用，请取消注释下面这行并注释掉上面那行（直白）
        run: gh release download -O LSPatch.jar --repo JingMatrix/LSPatch --pattern '*.jar'
        
      # 下载模块
      - name: Download Modules 下载模块
        run: |
          gh release download -O QAuxiliary.apk --repo cinit/QAuxiliary     --pattern '*arm64.apk'
          gh release download -O XAutoDaily.apk --repo LuckyPray/XAutoDaily --pattern '*.apk'
          gh release download -O QQCleaner.apk  --repo KitsunePie/QQCleaner --pattern '*.apk'

      # 开始修补QQ
      - name: Patch QQ 修补各版本QQ
        run: java -jar LSPatch.jar QQ-*.apk -m QAuxiliary.apk,XAutoDaily.apk,QQCleaner.apk -l 2

      # 获取模块版本信息
      - id: QAuxiliary
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: cinit/QAuxiliary
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: XAutoDaily
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: LuckyPray/XAutoDaily
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: QQCleaner
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: KitsunePie/QQCleaner
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: LSPatch
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: LSPosed/LSPatch
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      # 发布Release
      - name: Draft Release 发布Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-lspatched.apk
          tag_name: ${{ github.run_id }} # 存储库中每个工作流运行的唯一编号
          name: QQ Releases ${{ github.run_number }} # 仓库中特定工作流程每个运行的唯一编号（从 1 开始递增）。
          body: |
            仅在此发布最新修补的Release版本，标有“latest”的是基于最新版本QQ修补的版本。

            ### 本次打包使用的模块
            | 模块名称 | 模块版本 | 查看项目 |
            | ------- | -------- | ------- |
            | QAuxiliary | ${{ steps.QAuxiliary.outputs.release }} | [点击跳转](https://github.com/cinit/QAuxiliary) |
            | XAutoDaily | ${{ steps.XAutoDaily.outputs.release }} | [点击跳转](https://github.com/LuckyPray/XAutoDaily) |
            | QQCleaner  | ${{ steps.QQCleaner.outputs.release }}  | [点击跳转](https://github.com/KitsunePie/QQCleaner) |

            <details><summary>点击展开模块更新详情</summary>
            #### QAuxiliary
            ${{ steps.QAuxiliary.outputs.description }}
            #### XAutoDaily
            ${{ steps.XAutoDaily.outputs.description }}
            #### QQCleaner
            ${{ steps.QQCleaner.outputs.description }}
            #### [LSPatch](https://github.com/JingMatrix/LSPatch)版本：${{ steps.LSPatch.outputs.release }}
